name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT
        # Запускаем SUT,
        # имя файла SUT будет отличаться в каждой задаче.
        # & означает, что в фоновом режиме не блокируем терминал для запуска тестов,
        # обязательно должен быть для запуска SUT в CI
        run: java -jar ./artifacts/app-mbank.jar &
      - name: Wait for SUT to be ready
        run: |
          for i in {1..5}; do
            nc -zv localhost 9999 && echo "SUT is ready" && exit 0 || echo "Waiting for SUT..."
            sleep 1
          done
          exit 1
      - name: Build with Gradle
        # Запускаем автотесты
        # Для проектов на базе Selenide необходимо добавить параметр для запуска браузера
        # в headless режиме -Dselenide.headless=true, параметр --info должен остаться
        run: ./gradlew test --info